// Local pixel comparison: measures template coverage and ink placement, not stroke order.
function traceMetrics(target,ink,size){
 const dilate=(mask,r)=>{const n=size+1,sum=new Uint32Array(n*n),out=new Uint8Array(size*size);for(let y=0;y<size;y++){let row=0;for(let x=0;x<size;x++){row+=mask[y*size+x];sum[(y+1)*n+x+1]=sum[y*n+x+1]+row}}for(let y=0;y<size;y++)for(let x=0;x<size;x++){const l=Math.max(0,x-r),t=Math.max(0,y-r),rr=Math.min(size,x+r+1),b=Math.min(size,y+r+1);out[y*size+x]=+(sum[b*n+rr]-sum[t*n+rr]-sum[b*n+l]+sum[t*n+l]>0)}return out};
 const nearTarget=dilate(target,4),nearInk=dilate(ink,5);let t=0,i=0,covered=0,on=0;for(let p=0;p<target.length;p++){if(target[p]){t++;covered+=nearInk[p]}if(ink[p]){i++;on+=nearTarget[p]}}const coverage=t?covered/t:0,precision=i?on/i:0;return {empty:i<8,coverage,precision,score:Math.round(100*(coverage+precision?2*coverage*precision/(coverage+precision):0))};
}
function mountTracing(d){
 const chars=Array.from(d.word),states=chars.map(()=>({paths:[],score:null}));let ci=0,active=null;const size=320;
 $('#game').innerHTML=`<div class="write-heading"><span class="word">${d.word}</span><span class="pinyin">${d.pinyin}</span></div><div id="traceChars" class="trace-chars"></div><div class="trace-board"><canvas id="traceGuide" width="320" height="320" aria-hidden="true"></canvas><canvas id="traceInk" width="320" height="320" aria-label="沿浅红色字形描写，可用鼠标、手指或触控笔"></canvas></div><p class="hint trace-note">沿浅红色字形慢慢描 · 评分仅衡量描红贴合度，不判断笔顺和书法</p><div id="traceResult" role="status" aria-live="polite"></div>`;
 const guide=$('#traceGuide'),canvas=$('#traceInk'),g=guide.getContext('2d'),ctx=canvas.getContext('2d'),mask=document.createElement('canvas');mask.width=mask.height=size;const m=mask.getContext('2d',{willReadFrequently:true});let target;
 function drawStroke(path){ctx.strokeStyle='#c83946';ctx.fillStyle='#c83946';ctx.lineWidth=9;ctx.lineCap=ctx.lineJoin='round';if(path.length===1){ctx.beginPath();ctx.arc(path[0].x,path[0].y,4.5,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.moveTo(path[0].x,path[0].y);for(const p of path.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke()}}
 function redraw(){ctx.clearRect(0,0,size,size);states[ci].paths.forEach(drawStroke)}
 function show(){active=null;$('#traceChars').innerHTML=chars.map((ch,i)=>`<button class="subtle ${i===ci?'chosen':''}" data-trace-char="${i}">${ch}${states[i].score===null?'':' · '+states[i].score+'分'}</button>`).join('');document.querySelectorAll('[data-trace-char]').forEach(b=>b.onclick=()=>{ci=Number(b.dataset.traceChar);show()});g.clearRect(0,0,size,size);g.strokeStyle='#ead1d1';g.lineWidth=1;g.setLineDash([5,5]);g.beginPath();g.moveTo(160,0);g.lineTo(160,320);g.moveTo(0,160);g.lineTo(320,160);g.moveTo(0,0);g.lineTo(320,320);g.moveTo(320,0);g.lineTo(0,320);g.stroke();m.clearRect(0,0,size,size);m.font='240px "Kaiti SC", KaiTi, STKaiti, "Noto Serif CJK SC", serif';m.textAlign='center';m.textBaseline='middle';m.fillStyle='#000';m.fillText(chars[ci],160,170);const pixels=m.getImageData(0,0,size,size).data;target=Uint8Array.from({length:size*size},(_,i)=>+(pixels[i*4+3]>60));g.save();g.globalAlpha=.20;g.drawImage(mask,0,0);g.globalCompositeOperation='source-atop';g.fillStyle='#bf4b50';g.fillRect(0,0,size,size);g.restore();redraw();$('#traceResult').textContent=states[ci].score===null?`第 ${ci+1} / ${chars.length} 个字：${chars[ci]}`:`「${chars[ci]}」描红贴合度：${states[ci].score} 分`}
 function pos(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*size/r.width,y:(e.clientY-r.top)*size/r.height}}
 canvas.onpointerdown=e=>{if(e.button!==0&&e.pointerType==='mouse')return;if(active)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);active={id:e.pointerId,path:[pos(e)]};states[ci].paths.push(active.path);states[ci].score=null;$('#traceResult').textContent='写好后，点击“看看评分”。';drawStroke(active.path)};
 canvas.onpointermove=e=>{if(!active||active.id!==e.pointerId)return;e.preventDefault();active.path.push(pos(e));redraw()};canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=()=>{active=null};
 action('擦掉重写',()=>{states[ci]={paths:[],score:null};show()});
 action('看看评分',()=>{const pixels=ctx.getImageData(0,0,size,size).data,ink=Uint8Array.from({length:size*size},(_,i)=>+(pixels[i*4+3]>60));const r=traceMetrics(target,ink,size);if(r.empty){$('#traceResult').textContent='先沿着字形写一写，再来评分吧。';return}states[ci].score=r.score;show();$('#traceResult').innerHTML=`<strong>描红贴合度 ${r.score} / 100</strong><br><span>覆盖 ${Math.round(r.coverage*100)}% · 字形内笔迹 ${Math.round(r.precision*100)}%</span><p>${r.coverage<.65?'还有一些浅色笔画没描到，找一找。':r.precision<.7?'有些笔迹跑到字形外了，放慢一点试试。':'描得越来越贴合了，继续保持！'}</p>`},true);
 if(chars.length>1)action('下一个字',()=>{ci=(ci+1)%chars.length;show()});action(journey?'完成整套练习':'下一个字词',next);show();
}
